### ISSUE TITLE
Cannot launch example

### ISSUE THREAD

**Issue by MHJena** [savantas/MAGMa-plus#1]
Hey,

i am trying to use MAGMa-plus. I have downloaded everything accordingly and am trying to compute the example given.

Everything works fine until i enter this command from the example:

	python MAGMa_plus.py annotate -c 0 -d 0 -b 3 -w 1 -s hmdb output.db

See stacktrace below. I have created an HMDB database by using the python script beforehand and set the correct path to that h,db database in the .ini file.

Any help would be appreciated.

`python MAGMa_plus.py annotate -c 0 -d 0 -b 3 -w 1 -s hmdb output.db
Parameter settings A
Traceback (most recent call last):
  File "MAGMa_plus.py", line 435, in <module>
    main()
  File "MAGMa_plus.py", line 413, in main
    magmacommand.run(magma_arguments_l)
  File "/home/carsten/MAGMa-plus-master/MAGMa_script.py", line 249, in run
    return args.func(args)
  File "/home/carsten/MAGMa-plus-master/MAGMa_script.py", line 189, in annotate
    annotate_engine = magma_session.get_annotate_engine(skip_fragmentation=args.skip_fragmentation, max_broken_bonds=args.max_broken_bonds, max_water_losses=args.max_water_losses, ms_intensity_cutoff=args.ms_intensity_cutoff, msms_intensity_cutoff=args.msms_intensity_cutoff, use_all_peaks=args.use_all_peaks, adducts=args.adducts, force_adduct=args.force_adduct, max_charge=args.max_charge, call_back_url=args.call_back_url)
  File "/home/carsten/MAGMa-plus-master/magma/init.py", line 75, in get_annotate_engine
    return AnnotateEngine(self.db_session, skip_fragmentation, max_broken_bonds, max_water_losses, ms_intensity_cutoff, msms_intensity_cutoff, use_all_peaks, adducts, force_adduct, max_charge, call_back_url)
  File "/home/carsten/MAGMa-plus-master/magma/init.py", line 761, in init
    print ('SETTINGS FOR MATCHING PRECURSOR IONS AND CANDIDATES:')
TypeError: unicode argument expected, got 'str'`

**Comment by savantas** [comment]
Hello,

Your question reached me well.
I am in a busy period currently, but I will try to look into this as soon
as possible.

Dries
